### ISSUE TITLE
0.0.4版本无法注册

### ISSUE THREAD

**Issue by THYuyukoZLAK** [zhishixiang/AutoWhitelist-Client#1]
如图，在awl.json中输入secret上传试卷后运行程序，反复提示正在注册
![20220807165234](https://user-images.githubusercontent.com/109353165/183283469-a8842039-63cb-4bec-a2d8-ec8622653a16.png)

**Comment by zhishixiang** [comment]
这是挺古老的问题了，从开发以来一直没能修复，只能等慢慢修了。
~~其实python版问题相当多，建议等fabric和spigot版~~
